// Mocks generated by Mockito 5.4.6 from annotations
// in show_movie_app/test/app/domain/usecases/get_movie_popular_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:show_movie_app/app/core/error/failures.dart' as _i5;
import 'package:show_movie_app/app/features/domain/entities/movie_detail_entity.dart'
    as _i7;
import 'package:show_movie_app/app/features/domain/entities/movie_entity.dart' as _i6;
import 'package:show_movie_app/app/features/domain/repositories/movie_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>
  getMoviePopular() =>
      (super.noSuchMethod(
            Invocation.method(#getMoviePopular, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.MovieEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.MovieEntity>>(
                this,
                Invocation.method(#getMoviePopular, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>
  getMovieFreeToWatch() =>
      (super.noSuchMethod(
            Invocation.method(#getMovieFreeToWatch, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.MovieEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.MovieEntity>>(
                this,
                Invocation.method(#getMovieFreeToWatch, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MovieEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetailEntity>> getMovieDetail(
    int? movieId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [movieId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, _i7.MovieDetailEntity>
            >.value(
              _FakeEither_0<_i5.Failure, _i7.MovieDetailEntity>(
                this,
                Invocation.method(#getMovieDetail, [movieId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetailEntity>>);
}
